using System.Text.Json;
using LoanPlatform.Common.AI;
using LoanPlatform.Common.Auth;
using LoanPlatform.Common.EventBus;
using LoanPlatform.Common.Logging;
using LoanPlatform.Contracts.Events;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UnderwritingService.Repositories;

namespace UnderwritingService.Controllers;

public record ManualEvaluateRequest(string CustomerId, decimal RequestedAmount, int CreditScore, bool IdentityConfirmed, decimal MonthlyIncome, decimal ExistingMonthlyDebt, decimal VehicleValue, int TermMonths = 60, string Channel = "Online");

[ApiController]
[Route("api/underwriting")]
[Authorize]
public class UnderwritingController : ControllerBase
{
    private readonly IDecisionRepository _repository;
    private readonly IEventBus _eventBus;
    private readonly IOriginationApiClient _originationClient;
    private readonly IClaudeUnderwritingCopilotService _copilotService;
    private readonly ILogger<UnderwritingController> _logger;

    public UnderwritingController(
        IDecisionRepository repository,
        IEventBus eventBus,
        IOriginationApiClient originationClient,
        IClaudeUnderwritingCopilotService copilotService,
        ILogger<UnderwritingController> logger)
    {
        _repository = repository;
        _eventBus = eventBus;
        _originationClient = originationClient;
        _copilotService = copilotService;
        _logger = logger;
    }

    [HttpGet("{applicationId}/decision")]
    public IActionResult GetDecision(string applicationId)
    {
        var record = _repository.GetByApplicationId(applicationId);
        return record is null
            ? NotFound(new { error = $"No decision found for application {applicationId} — it may still be processing." })
            : Ok(record);
    }

    /// <summary>Just the risk-relevant figures — credit score, DTI, LTV, approval outcome — without the full decision payload.</summary>
    [HttpGet("{applicationId}/risk-score")]
    public IActionResult GetRiskScore(string applicationId)
    {
        var record = _repository.GetByApplicationId(applicationId);
        return record is null
            ? NotFound(new { error = $"No risk evaluation found for application {applicationId}." })
            : Ok(new { record.ApplicationId, record.CreditScore, record.DebtToIncomeRatio, record.LoanToValueRatio, record.Approved });
    }

    /// <summary>
    /// Underwriter co-pilot: an internal-only, advisory summary of an
    /// application for a human underwriter's own review — risk factors,
    /// inconsistencies, and suggested stipulations, generated by Claude
    /// from this application's real data. Deliberately manual: this is
    /// only ever called when a human clicks "Generate summary" in the UI,
    /// never automatically for every application that reaches
    /// underwriting, so the Anthropic API is only charged for applications
    /// someone actually opens and asks about.
    ///
    /// Idempotent by default: once a summary has been generated for an
    /// application, this returns the cached copy (stored on the decision
    /// record — see UpdateCopilotSummary) on every subsequent call,
    /// without calling Claude again, unless ?regenerate=true is passed
    /// explicitly. Re-viewing the same application's review screen never
    /// silently re-triggers a paid API call.
    ///
    /// This never returns or implies an approve/deny recommendation — see
    /// UnderwritingCopilotSchemas and ClaudeUnderwritingCopilotService's
    /// system prompt for why that's enforced at the schema level, not just
    /// asked for nicely. The output is for the underwriter's own reading,
    /// never shown or sent to the applicant.
    /// </summary>
    [HttpPost("{applicationId}/copilot-summary")]
    public async Task<IActionResult> GetCopilotSummary(string applicationId, [FromQuery] bool regenerate = false)
    {
        var record = _repository.GetByApplicationId(applicationId);
        if (record is null)
        {
            return NotFound(new { error = $"No decision found for application {applicationId} — it may still be processing. The co-pilot summarizes an existing decision; it doesn't run ahead of one." });
        }

        if (!regenerate && record.CopilotSummaryJson is not null)
        {
            _logger.Trace(applicationId, "CopilotSummary.CacheHit", "Returning previously generated co-pilot summary — no Claude call made", new { record.CopilotGeneratedAt });
            return Ok(new
            {
                applicationId,
                cached = true,
                generatedAt = record.CopilotGeneratedAt,
                summary = JsonSerializer.Deserialize<JsonElement>(record.CopilotSummaryJson),
            });
        }

        _logger.Trace(applicationId, "CopilotSummary.Generate.Start", "Generating a fresh co-pilot summary via Claude", new { regenerate });

        // Forward the caller's own bearer token to Origination rather than
        // acquiring a separate one — see OriginationApiClient's remarks on
        // why this works (same Entra ID app registration validates both).
        var bearer = Request.Headers.Authorization.ToString();
        var applicationJson = await _originationClient.GetApplicationJsonAsync(applicationId, bearer);
        if (applicationJson is null)
        {
            _logger.Trace(applicationId, "CopilotSummary.Generate.OriginationUnreachable", "Could not fetch application from Origination");
            return StatusCode(StatusCodes.Status502BadGateway, new
            {
                error = $"Could not fetch application {applicationId} from Origination — it may not exist, or Origination may be unreachable right now.",
            });
        }

        var decisionJson = JsonSerializer.Serialize(record);
        var result = await _copilotService.GenerateSummaryAsync(applicationId, applicationJson, decisionJson);

        if (!result.Success || result.Data is null)
        {
            _logger.Trace(applicationId, "CopilotSummary.Generate.Failed", "Claude did not return a usable summary", new { result.Error });
            return UnprocessableEntity(new { error = result.Error ?? "Claude did not return a usable summary." });
        }

        var generatedAt = DateTimeOffset.UtcNow;
        _repository.UpdateCopilotSummary(applicationId, result.Data.Value.GetRawText(), generatedAt);
        _logger.Trace(applicationId, "CopilotSummary.Generate.Done", "Co-pilot summary generated and cached against the decision record");

        return Ok(new
        {
            applicationId,
            cached = false,
            generatedAt,
            summary = result.Data,
        });
    }

    /// <summary>
    /// Manually triggers a risk evaluation outside the normal event flow —
    /// e.g. for testing the risk engine directly, or a manual underwriter
    /// override scenario. Runs the same RiskEngine and publishes the same
    /// UnderwritingDecisionEvent as the automatic event-driven path, so
    /// Funding reacts identically either way.
    ///
    /// BUG FIX: this endpoint used to let a caller silently overwrite an
    /// existing decision no matter what — including one Funding had
    /// already acted on. A denied re-evaluation could replace an approved
    /// decision with no trace that money had already moved against the
    /// original approval. Now refuses to re-evaluate at all once the
    /// existing decision is marked Funded (see LoanFundedEventHandler in
    /// EventHandlers.cs, which sets that flag). The manual-override use
    /// case this endpoint exists for is still fully supported for any
    /// application that hasn't been funded yet — this only locks a
    /// decision down after real money has moved on the strength of it.
    /// </summary>
    [HttpPost("{applicationId}/evaluate")]
    public async Task<IActionResult> Evaluate(string applicationId, [FromBody] ManualEvaluateRequest request)
    {
        _logger.Trace(applicationId, "Evaluate.Start", "Manual evaluate_application called", new { request.RequestedAmount, request.CreditScore, request.ExistingMonthlyDebt, request.MonthlyIncome, request.VehicleValue, request.TermMonths });

        var existingDecision = _repository.GetByApplicationId(applicationId);
        if (existingDecision is { Funded: true })
        {
            _logger.Trace(applicationId, "Evaluate.Refused", "Refused: existing decision already marked Funded");
            return Conflict(new
            {
                error = $"Application {applicationId} has already been funded based on its current decision and can no longer be re-evaluated.",
            });
        }

        var decision = RiskEngine.Evaluate(
            request.CreditScore, request.IdentityConfirmed, request.RequestedAmount,
            request.MonthlyIncome, request.ExistingMonthlyDebt, request.VehicleValue);
        _logger.Trace(applicationId, "Evaluate.RiskEngineResult", "RiskEngine.Evaluate returned", new { decision.Approved, decision.DebtToIncomeRatio, decision.LoanToValueRatio, decision.ApprovedAmount, decision.Reason });

        var record = _repository.Add(new UnderwritingRecord(
            applicationId, decision.Approved, decision.Reason,
            decision.ApprovedAmount, decision.InterestRate, request.CreditScore,
            decision.DebtToIncomeRatio, decision.LoanToValueRatio, decision.Stipulations, DateTimeOffset.UtcNow));

        _logger.LogInformation("Manual evaluation for {ApplicationId}: Approved={Approved}", applicationId, decision.Approved);

        await _eventBus.PublishAsync(new LoanPlatform.Contracts.Events.UnderwritingDecisionEvent
        {
            ApplicationId = applicationId,
            Approved = decision.Approved,
            Reason = decision.Reason,
            ApprovedAmount = decision.ApprovedAmount,
            InterestRate = decision.InterestRate,
            DebtToIncomeRatio = decision.DebtToIncomeRatio,
            LoanToValueRatio = decision.LoanToValueRatio,
            Stipulations = decision.Stipulations,
            TermMonths = request.TermMonths,
            Channel = request.Channel,
        });
        _logger.Trace(applicationId, "Evaluate.EventPublished", "UnderwritingDecisionEvent published");

        return Ok(record);
    }
}
