// AZURE MIGRATION: new file.
//
// SERVICE_URLS used to be a hardcoded object in app.ts:
//   origination: 'http://localhost:5100', ...
// which only worked locally, where the browser and every container share
// one machine. Once deployed, each backend has its own real HTTPS URL that
// isn't known until after the Container Apps are provisioned — so instead
// of baking URLs into the JS bundle at build time, we fetch them from
// /config.json at app startup, generated by ui/docker-entrypoint.sh from
// environment variables when the UI container starts (see infra/main.bicep
// for where ORIGINATION_URL etc. are set per environment).
//
// The object identity is kept stable (Object.assign, not reassignment) so
// every existing `SERVICE_URLS.origination` usage elsewhere in app.ts keeps
// working unchanged — they all read from the same object reference, which
// just gets its values filled in before the component ever renders.

export const SERVICE_URLS = {
  origination: 'http://localhost:5100',
  underwriting: 'http://localhost:5101',
  funding: 'http://localhost:5102',
  servicing: 'http://localhost:5103',
};

/**
 * Loads real service URLs from /config.json (produced at container start —
 * see ui/docker-entrypoint.sh and ui/public/config.template.json) and
 * overwrites the defaults above in place.
 *
 * Safe to call in any environment: if /config.json 404s (e.g. running via
 * `ng serve` directly, outside the container, or the file genuinely hasn't
 * been generated yet), this quietly keeps the localhost defaults — the
 * same behavior this app already had before the Azure migration.
 *
 * Call and await this once, before bootstrapping the app — see main.ts.
 */
export async function loadServiceConfig(): Promise<void> {
  try {
    const response = await fetch('/config.json', { cache: 'no-store' });
    if (!response.ok) return;

    const overrides = await response.json();
    Object.assign(SERVICE_URLS, overrides);
  } catch {
    // /config.json missing or unreachable (e.g. local `ng serve`) — the
    // localhost:5100-5103 defaults above are exactly right for that case.
  }
}
